### ISSUE TITLE
nodejs conversion

### ISSUE THREAD

**Issue by nicojanssens** [jschaeke/qbusMQTT#1]
Just fyi -- if you'd still consider converting your QBus lib to nodejs, I just published a JS lib supporting the basic interactions with the EQOweb API.

More on [GH](https://github.com/nicojanssens/qbus-eqoweb-api) and [npm](https://www.npmjs.com/package/qbus-eqoweb-api).

**Comment by jschaeke** [comment]
Nice, thx! Will check it out and include it... one day ;-)

**Comment by jschaeke** [comment]
Seems today was the day ;)  https://github.com/jschaeke/qbusMqtt2
